<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uc_paybox_help ($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'entity.uc_payment_method.add_form' &&
      $route_match->getRawParameter('plugin_id') == 'uc_paybox') {
    return '<p>' . t('To accept PayBox payments, please ensure that demo mode is disabled.') . '</p>';
  }
  elseif ($route_name == 'entity.uc_payment_method.edit_form' &&
          $route_match->getParameter('uc_payment_method')->getPlugin()->getPluginId() == 'uc_paybox') {
    return '<p>' . t('To accept PayBox payments, please ensure that demo mode is disabled.') . '</p>';
  }
}